#!/usr/bin/env python3
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]


def text(path):
    return (ROOT / path).read_text(encoding='utf-8')


def write(path, value):
    (ROOT / path).write_text(value, encoding='utf-8')


def replace_once(path, old, new):
    s = text(path)
    count = s.count(old)
    if count != 1:
        raise SystemExit(f'{path}: expected exactly one match, got {count}: {old[:100]!r}')
    write(path, s.replace(old, new, 1))

# R01 — integrity check must persist truthful signed health and surface persistence/audit failure.
replace_once('includes/class-snfla-plugin.php', """\t\t\t$evidence = array(\n\t\t\t\t'checked_at_utc'    => gmdate( 'Y-m-d H:i:s' ),\n\t\t\t\t'source_unchanged'  => SNFLA_Inventory::unchanged(),\n\t\t\t\t'audit_chain'       => SNFLA_Audit::verify_chain(),\n\t\t\t\t'reconciliation_ok' => SNFLA_Reconciliation::validate_current_report(),\n\t\t\t);\n\t\t\t$evidence = SNFLA_Integrity::sign_evidence( $evidence );\n\t\t\tupdate_option( 'snfla_last_integrity_check', $evidence, false );\n\t\t\tSNFLA_Audit::record( 'daily_integrity_checked', 0, array( 'source_unchanged' => $evidence['source_unchanged'], 'audit_valid' => ! empty( $evidence['audit_chain']['valid'] ), 'reconciliation_ok' => $evidence['reconciliation_ok'] ) );\n""", """\t\t\t$chain = SNFLA_Audit::verify_chain();\n\t\t\t$source_unchanged = SNFLA_Inventory::unchanged();\n\t\t\t$reconciliation_ok = SNFLA_Reconciliation::validate_current_report();\n\t\t\t$audit_written = SNFLA_Audit::record( 'daily_integrity_checked', 0, array( 'source_unchanged' => $source_unchanged, 'audit_valid' => ! empty( $chain['valid'] ), 'reconciliation_ok' => $reconciliation_ok ) );\n\t\t\t$evidence = SNFLA_Integrity::sign_evidence( array(\n\t\t\t\t'checked_at_utc'    => gmdate( 'Y-m-d H:i:s' ),\n\t\t\t\t'source_unchanged'  => $source_unchanged,\n\t\t\t\t'audit_chain'       => $chain,\n\t\t\t\t'reconciliation_ok' => $reconciliation_ok,\n\t\t\t\t'audit_written'     => $audit_written,\n\t\t\t\t'ok'                => $source_unchanged && ! empty( $chain['valid'] ) && $reconciliation_ok && $audit_written,\n\t\t\t) );\n\t\t\t$persisted = update_option( 'snfla_last_integrity_check', $evidence, false ) || get_option( 'snfla_last_integrity_check', array() ) === $evidence;\n\t\t\tif ( ! $persisted || ! $audit_written ) {\n\t\t\t\tdo_action( 'snfla_operational_alert_v1', array( 'code' => 'daily_integrity_evidence_failed', 'severity' => 'critical' ) );\n\t\t\t}\n""")

# R02 — persisted lifecycle version corruption must fail closed rather than normalize to 1.
replace_once('includes/class-snfla-schema.php', """\tpublic static function version() {\n\t\treturn max( 1, absint( get_option( self::STATE_VERSION_OPTION, 1 ) ) );\n\t}\n""", """\tpublic static function version() {\n\t\t$sentinel = new stdClass();\n\t\t$stored = get_option( self::STATE_VERSION_OPTION, $sentinel );\n\t\tif ( $stored === $sentinel ) { return 1; }\n\t\tif ( is_int( $stored ) || ( is_string( $stored ) && preg_match( '/^[1-9][0-9]*$/D', $stored ) ) ) {\n\t\t\t$version = (int) $stored;\n\t\t\treturn $version >= 1 ? $version : 0;\n\t\t}\n\t\treturn 0;\n\t}\n""")
replace_once('includes/class-snfla-schema.php', """\tpublic static function state_valid() {\n\t\treturn in_array( self::state(), self::states(), true );\n\t}\n""", """\tpublic static function state_valid() {\n\t\treturn in_array( self::state(), self::states(), true ) && self::version() >= 1;\n\t}\n""")
replace_once('includes/class-snfla-schema.php', """\t\t\t$version          = self::version();\n\t\t\tif ( self::INVALID_STATE === $current ) {\n""", """\t\t\t$version          = self::version();\n\t\t\tif ( self::INVALID_STATE === $current || $version < 1 ) {\n""")
replace_once('includes/class-snfla-schema.php', """\t\t$current = self::state();\n\t\tif ( self::INVALID_STATE === $current ) {\n""", """\t\t$current = self::state();\n\t\tif ( self::INVALID_STATE === $current || self::version() < 1 ) {\n""")
replace_once('includes/class-snfla-schema.php', """\t\t\t$version = self::version();\n\t\t\tif ( self::INVALID_STATE === $current ) {\n""", """\t\t\t$version = self::version();\n\t\t\tif ( self::INVALID_STATE === $current || $version < 1 ) {\n""")
replace_once('includes/class-snfla-schema.php', """\t\treturn array( 'state' => $state, 'version' => self::version(), 'valid' => in_array( $state, self::states(), true ) );\n""", """\t\t$version = self::version();\n\t\treturn array( 'state' => $state, 'version' => $version, 'valid' => in_array( $state, self::states(), true ) && $version >= 1 );\n""")

# R03 — lifecycle rollback must be verified after a partial state/version persistence failure.
replace_once('includes/class-snfla-schema.php', """\t\t\tif ( ! $state_ok || ! $version_ok ) {\n\t\t\t\tupdate_option( self::STATE_OPTION, $current, false );\n\t\t\t\tupdate_option( self::STATE_VERSION_OPTION, $version, false );\n\t\t\t\treturn new WP_Error( 'snfla_lifecycle_persist_failed', 'The lifecycle transition could not be persisted.', array( 'status' => 500 ) );\n\t\t\t}\n""", """\t\t\tif ( ! $state_ok || ! $version_ok ) {\n\t\t\t\tupdate_option( self::STATE_OPTION, $current, false );\n\t\t\t\tupdate_option( self::STATE_VERSION_OPTION, $version, false );\n\t\t\t\t$restored = self::state() === $current && self::version() === $version;\n\t\t\t\treturn new WP_Error( $restored ? 'snfla_lifecycle_persist_failed' : 'snfla_lifecycle_compensation_failed', $restored ? 'The lifecycle transition could not be persisted.' : 'Lifecycle persistence failed and the previous state/version pair could not be restored exactly.', array( 'status' => 500, 'manual_recovery_required' => ! $restored ) );\n\t\t\t}\n""")
replace_once('includes/class-snfla-schema.php', """\t\t\tif ( ! $state_ok || ! $version_ok ) {\n\t\t\t\tupdate_option( self::STATE_OPTION, $current, false );\n\t\t\t\tupdate_option( self::STATE_VERSION_OPTION, $version, false );\n\t\t\t\treturn new WP_Error( 'snfla_lifecycle_persist_failed', 'Rollback recovery state could not be persisted.', array( 'status' => 500 ) );\n\t\t\t}\n""", """\t\t\tif ( ! $state_ok || ! $version_ok ) {\n\t\t\t\tupdate_option( self::STATE_OPTION, $current, false );\n\t\t\t\tupdate_option( self::STATE_VERSION_OPTION, $version, false );\n\t\t\t\t$restored = self::state() === $current && self::version() === $version;\n\t\t\t\treturn new WP_Error( $restored ? 'snfla_lifecycle_persist_failed' : 'snfla_lifecycle_compensation_failed', $restored ? 'Rollback recovery state could not be persisted.' : 'Rollback recovery persistence failed and the previous lifecycle pair could not be restored exactly.', array( 'status' => 500, 'manual_recovery_required' => ! $restored ) );\n\t\t\t}\n""")

# R04 — checkpoint matching requires cryptographically shaped signatures, never empty equality.
replace_once('includes/class-snfla-integrity.php', """\t\t$stored_ids = self::normalized_ids( (array) ( $checkpoint['legacy_ids'] ?? array() ) );\n\t\treturn hash_equals( (string) ( $run['source_signature'] ?? '' ), (string) $source_signature )\n\t\t\t&& $stored_ids === self::normalized_ids( $legacy_ids );\n""", """\t\t$stored_ids = self::normalized_ids( (array) ( $checkpoint['legacy_ids'] ?? array() ) );\n\t\t$stored_signature = strtolower( (string) ( $run['source_signature'] ?? '' ) );\n\t\t$source_signature = strtolower( (string) $source_signature );\n\t\treturn 1 === preg_match( '/^[a-f0-9]{64}$/D', $stored_signature )\n\t\t\t&& 1 === preg_match( '/^[a-f0-9]{64}$/D', $source_signature )\n\t\t\t&& hash_equals( $stored_signature, $source_signature )\n\t\t\t&& $stored_ids === self::normalized_ids( $legacy_ids );\n""")

# R05 — malformed timestamp on a running operation is corrupt/stale, not immortal.
replace_once('includes/class-snfla-integrity.php', """\t\tif ( ! is_array( $run ) || 'running' !== ( $run['status'] ?? '' ) || empty( $run['started_at'] ) ) {\n\t\t\treturn false;\n\t\t}\n\t\t$started = strtotime( (string) $run['started_at'] . ' UTC' );\n\t\treturn false !== $started && $started < time() - self::STALE_RUN_SECONDS;\n""", """\t\tif ( ! is_array( $run ) || 'running' !== ( $run['status'] ?? '' ) ) { return false; }\n\t\tif ( empty( $run['started_at'] ) ) { return true; }\n\t\t$started = strtotime( (string) $run['started_at'] . ' UTC' );\n\t\treturn false === $started || $started < time() - self::STALE_RUN_SECONDS || $started > time() + 300;\n""")

# R06 — a corrupt matching audit event must fail the evidence query closed.
replace_once('includes/class-snfla-audit.php', """\t\t\t\tif ( ! is_array( $context ) || JSON_ERROR_NONE !== json_last_error() ) {\n\t\t\t\t\tcontinue;\n\t\t\t\t}\n""", """\t\t\t\tif ( ! is_array( $context ) || JSON_ERROR_NONE !== json_last_error() ) {\n\t\t\t\t\treturn false;\n\t\t\t\t}\n""")

# R07/R08 — UTF-8-safe audit truncation plus deterministic non-colliding normalized keys.
replace_once('includes/class-snfla-audit.php', """\t\t$out  = array();\n\t\tforeach ( array_slice( $context, 0, 100, true ) as $key => $value ) {\n\t\t\t$key = sanitize_key( (string) $key );\n\t\t\tif ( '' === $key ) { $key = 'field'; }\n""", """\t\t$out  = array();\n\t\t$key_index = 0;\n\t\tforeach ( array_slice( $context, 0, 100, true ) as $raw_key => $value ) {\n\t\t\t$key_index++;\n\t\t\t$raw_key_string = (string) $raw_key;\n\t\t\t$key = sanitize_key( $raw_key_string );\n\t\t\tif ( '' === $key ) { $key = 'field_' . substr( hash( 'sha256', $raw_key_string . '|' . $key_index ), 0, 12 ); }\n\t\t\twhile ( array_key_exists( $key, $out ) ) { $key .= '_' . $key_index; }\n""")
replace_once('includes/class-snfla-audit.php', """\t\t\t\t$out[ $key ] = substr( sanitize_text_field( is_object( $value ) ? get_class( $value ) : (string) $value ), 0, 300 );\n""", """\t\t\t\t$clean = sanitize_text_field( is_object( $value ) ? get_class( $value ) : (string) $value );\n\t\t\t\t$out[ $key ] = function_exists( 'mb_substr' ) ? mb_substr( $clean, 0, 300, 'UTF-8' ) : wp_check_invalid_utf8( substr( $clean, 0, 300 ), true );\n""")

# R09 — per-site adapter must never deactivate a network-wide obsolete plugin.
replace_once('includes/class-snfla-database.php', """\t\t\tif ( '' === $plugin ) {\n\t\t\t\tcontinue;\n\t\t\t}\n\t\t\tdeactivate_plugins( $plugin, true, $network );\n""", """\t\t\tif ( '' === $plugin ) { continue; }\n\t\t\tif ( $network ) {\n\t\t\t\treturn new WP_Error( 'snfla_network_legacy_runtime_requires_network_operator', 'A network-wide legacy publishing runtime was detected. A per-site File 04 activation must not mutate network-wide plugin state.', array( 'plugin_hash' => hash( 'sha256', $plugin ) ) );\n\t\t\t}\n\t\t\tdeactivate_plugins( $plugin, true, false );\n""")

# R10 — rewrite-rules handover checksum cannot accept encoding failure.
replace_once('includes/class-snfla-database.php', """\t\t$snapshot = array(\n\t\t\t'schema'                 => 3,\n""", """\t\t$rewrite_rules_encoded = wp_json_encode( SNFLA_Checksum::canonicalize( (array) get_option( 'rewrite_rules', array() ) ), JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES );\n\t\tif ( ! is_string( $rewrite_rules_encoded ) ) { return new WP_Error( 'snfla_rewrite_rules_evidence_encoding_failed', 'Rewrite-rule handover evidence could not be encoded safely.' ); }\n\t\t$snapshot = array(\n\t\t\t'schema'                 => 4,\n""")
replace_once('includes/class-snfla-database.php', """\t\t\t'rewrite_rules_checksum' => hash( 'sha256', wp_json_encode( get_option( 'rewrite_rules', array() ) ) ),\n""", """\t\t\t'rewrite_rules_checksum' => hash( 'sha256', $rewrite_rules_encoded ),\n""")

# R11 — present-but-corrupt lifecycle options are not treated as absent during activation.
replace_once('includes/class-snfla-database.php', """\t\tif ( ! get_option( SNFLA_Schema::STATE_OPTION, false ) ) {\n\t\t\tadd_option( SNFLA_Schema::STATE_OPTION, 'legacy_active', '', false );\n\t\t}\n\t\tif ( ! get_option( SNFLA_Schema::STATE_VERSION_OPTION, false ) ) {\n\t\t\tadd_option( SNFLA_Schema::STATE_VERSION_OPTION, 1, '', false );\n\t\t}\n""", """\t\t$state_sentinel = new stdClass();\n\t\t$stored_state = get_option( SNFLA_Schema::STATE_OPTION, $state_sentinel );\n\t\t$version_sentinel = new stdClass();\n\t\t$stored_version = get_option( SNFLA_Schema::STATE_VERSION_OPTION, $version_sentinel );\n\t\tif ( $stored_state === $state_sentinel ) {\n\t\t\tif ( ! add_option( SNFLA_Schema::STATE_OPTION, 'legacy_active', '', false ) ) { self::compensate_or_fail( $snapshot, $actor_id, new WP_Error( 'snfla_lifecycle_state_init_failed', 'Initial lifecycle state could not be persisted.' ) ); }\n\t\t} elseif ( ! in_array( sanitize_key( (string) $stored_state ), SNFLA_Schema::states(), true ) ) {\n\t\t\tself::compensate_or_fail( $snapshot, $actor_id, new WP_Error( 'snfla_lifecycle_state_corrupt', 'A corrupt persisted lifecycle state blocks activation.' ) );\n\t\t}\n\t\tif ( $stored_version === $version_sentinel ) {\n\t\t\tif ( ! add_option( SNFLA_Schema::STATE_VERSION_OPTION, 1, '', false ) ) { self::compensate_or_fail( $snapshot, $actor_id, new WP_Error( 'snfla_lifecycle_version_init_failed', 'Initial lifecycle version could not be persisted.' ) ); }\n\t\t} elseif ( SNFLA_Schema::version() < 1 ) {\n\t\t\tself::compensate_or_fail( $snapshot, $actor_id, new WP_Error( 'snfla_lifecycle_version_corrupt', 'A corrupt persisted lifecycle version blocks activation.' ) );\n\t\t}\n""")

# R12 — an option map cannot commandeer unrelated pages unless the page still contains a known legacy shortcode.
replace_once('includes/class-snfla-database.php', """\t\t\tif ( ! $page instanceof WP_Post || 'page' !== $page->post_type ) {\n\t\t\t\tcontinue;\n\t\t\t}\n\t\t\t$records[] = array(\n""", """\t\t\tif ( ! $page instanceof WP_Post || 'page' !== $page->post_type ) { continue; }\n\t\t\t$has_legacy_shortcode = false;\n\t\t\tforeach ( array( 'sabri_news_home', 'sabri_news_feed', 'sabri_publish_form', 'sabri_publication_feed', 'sabri_my_publication_reports' ) as $shortcode ) {\n\t\t\t\tif ( has_shortcode( (string) $page->post_content, $shortcode ) ) { $has_legacy_shortcode = true; break; }\n\t\t\t}\n\t\t\tif ( ! $has_legacy_shortcode ) { continue; }\n\t\t\t$records[] = array(\n""")

# R13 — quarantine revalidates content, slug and status captured by the activation snapshot.
replace_once('includes/class-snfla-database.php', """\t\t\tif ( ! hash_equals( (string) ( $record['content_checksum'] ?? '' ), hash( 'sha256', (string) $page->post_content ) ) ) {\n\t\t\t\treturn new WP_Error( 'snfla_legacy_page_changed', 'A legacy File 04 page changed during activation and was not quarantined.', array( 'page_id' => $page_id ) );\n\t\t\t}\n\t\t\t$original_status = sanitize_key( (string) ( $record['original_status'] ?? $page->post_status ) );\n""", """\t\t\t$original_status = sanitize_key( (string) ( $record['original_status'] ?? '' ) );\n\t\t\t$content_matches = hash_equals( (string) ( $record['content_checksum'] ?? '' ), hash( 'sha256', (string) $page->post_content ) );\n\t\t\t$slug_matches = hash_equals( (string) ( $record['slug_checksum'] ?? '' ), hash( 'sha256', (string) $page->post_name ) );\n\t\t\t$status_matches = '' !== $original_status && sanitize_key( (string) $page->post_status ) === $original_status;\n\t\t\tif ( ! $content_matches || ! $slug_matches || ! $status_matches ) {\n\t\t\t\treturn new WP_Error( 'snfla_legacy_page_changed', 'A legacy File 04 page changed after the activation snapshot and was not quarantined.', array( 'page_id' => $page_id ) );\n\t\t\t}\n""")

# R14 — schema upgrades are serialized and leave explicit health evidence.
replace_once('includes/class-snfla-database.php', """\tpublic static function maybe_upgrade() {\n\t\tif ( SNFLA_SCHEMA_VERSION === (string) get_option( 'snfla_schema_version', '' ) ) {\n\t\t\treturn;\n\t\t}\n\t\tself::install();\n\t\t$verified = self::verify_schema();\n""", """\tpublic static function maybe_upgrade() {\n\t\tif ( SNFLA_SCHEMA_VERSION === (string) get_option( 'snfla_schema_version', '' ) ) { return; }\n\t\tif ( ! self::acquire_lock( 'schema_upgrade', 5 ) ) {\n\t\t\tself::persist_option( 'snfla_schema_health', array( 'ok' => false, 'code' => 'snfla_schema_upgrade_locked', 'checked_at_utc' => gmdate( 'Y-m-d H:i:s' ) ) );\n\t\t\treturn;\n\t\t}\n\t\ttry {\n\t\tself::install();\n\t\t$verified = self::verify_schema();\n""")
replace_once('includes/class-snfla-database.php', """\t\tself::persist_option( 'snfla_schema_version', SNFLA_SCHEMA_VERSION );\n\t\tself::persist_option( 'snfla_schema_health', array( 'ok' => true, 'checked_at_utc' => gmdate( 'Y-m-d H:i:s' ) ) );\n\t}\n\n\tprivate static function capture_activation_handover""", """\t\tself::persist_option( 'snfla_schema_version', SNFLA_SCHEMA_VERSION );\n\t\tself::persist_option( 'snfla_schema_health', array( 'ok' => true, 'checked_at_utc' => gmdate( 'Y-m-d H:i:s' ) ) );\n\t\t} finally { self::release_lock( 'schema_upgrade' ); }\n\t}\n\n\tpublic static function schema_healthy() {\n\t\tif ( SNFLA_SCHEMA_VERSION !== (string) get_option( 'snfla_schema_version', '' ) ) { return false; }\n\t\t$health = get_option( 'snfla_schema_health', array() );\n\t\treturn ! is_array( $health ) || ! array_key_exists( 'ok', $health ) || ! empty( $health['ok'] );\n\t}\n\n\tprivate static function capture_activation_handover""")

# R15/R16 — verify every declared column and the exact ordered columns of named indexes.
replace_once('includes/class-snfla-database.php', """\t\t$required = array(\n\t\t\t'runs'               => array( 'id', 'run_uuid', 'operation', 'status', 'source_signature' ),\n\t\t\t'map'                => array( 'id', 'legacy_id', 'target_id', 'status', 'source_checksum', 'interaction_ledger_json' ),\n\t\t\t'conflicts'          => array( 'id', 'legacy_id', 'conflict_code', 'fingerprint', 'status' ),\n\t\t\t'audit'              => array( 'id', 'event_uuid', 'event_hash', 'prev_hash', 'created_at' ),\n\t\t\t'dry_run'            => array( 'id', 'source_signature', 'legacy_id', 'source_checksum', 'eligible', 'conflict_codes_json' ),\n\t\t\t'interaction_ledger' => array( 'id', 'legacy_id', 'target_id', 'kind', 'source_row_id', 'canonical_row_id', 'contribution_count', 'original_json', 'status' ),\n\t\t);\n""", """\t\t$required = array(\n\t\t\t'runs' => array( 'id','run_uuid','operation','status','actor_digest','idempotency_hash','source_signature','checkpoint_json','summary_json','started_at','finished_at' ),\n\t\t\t'map' => array( 'id','legacy_id','target_id','target_type','status','source_checksum','target_checksum','run_uuid','interaction_ledger_json','last_error_code','created_at','updated_at' ),\n\t\t\t'conflicts' => array( 'id','legacy_id','conflict_code','severity','fingerprint','status','redacted_context_json','run_uuid','created_at','resolved_at' ),\n\t\t\t'audit' => array( 'id','event_uuid','actor_digest','action','object_ref','context_json','prev_hash','event_hash','created_at' ),\n\t\t\t'dry_run' => array( 'id','run_uuid','source_signature','legacy_id','source_checksum','target_type','eligible','conflict_codes_json','created_at' ),\n\t\t\t'interaction_ledger' => array( 'id','legacy_id','target_id','kind','source_row_id','canonical_row_id','contribution_count','original_json','created_by_migration','status','created_at','updated_at' ),\n\t\t);\n""")
replace_once('includes/class-snfla-database.php', """\t\t$required_indexes = array(\n\t\t\t'runs'               => array( 'run_uuid' => true, 'operation_idempotency' => true ),\n\t\t\t'map'                => array( 'legacy_id' => true ),\n\t\t\t'conflicts'          => array( 'conflict_fingerprint' => true ),\n\t\t\t'audit'              => array( 'event_uuid' => true ),\n\t\t\t'dry_run'            => array( 'run_legacy' => true, 'source_legacy' => false ),\n\t\t\t'interaction_ledger' => array( 'source_row' => true, 'canonical_row' => false ),\n\t\t);\n""", """\t\t$required_indexes = array(\n\t\t\t'runs' => array( 'run_uuid' => array( true, array('run_uuid') ), 'operation_idempotency' => array( true, array('operation','idempotency_hash') ) ),\n\t\t\t'map' => array( 'legacy_id' => array( true, array('legacy_id') ) ),\n\t\t\t'conflicts' => array( 'conflict_fingerprint' => array( true, array('fingerprint') ) ),\n\t\t\t'audit' => array( 'event_uuid' => array( true, array('event_uuid') ) ),\n\t\t\t'dry_run' => array( 'run_legacy' => array( true, array('run_uuid','legacy_id') ), 'source_legacy' => array( false, array('source_signature','legacy_id') ) ),\n\t\t\t'interaction_ledger' => array( 'source_row' => array( true, array('legacy_id','kind','source_row_id') ), 'canonical_row' => array( false, array('kind','canonical_row_id') ) ),\n\t\t);\n""")
replace_once('includes/class-snfla-database.php', """\t\t\t$actual_indexes = array();\n\t\t\tforeach ( $rows as $index ) {\n\t\t\t\t$name = (string) ( $index['Key_name'] ?? '' );\n\t\t\t\tif ( '' !== $name ) {\n\t\t\t\t\t$actual_indexes[ $name ] = 0 === absint( $index['Non_unique'] ?? 1 );\n\t\t\t\t}\n\t\t\t}\n\t\t\tforeach ( $index_rules as $name => $must_be_unique ) {\n\t\t\t\tif ( ! array_key_exists( $name, $actual_indexes ) ) {\n\t\t\t\t\t$errors[] = $key . '_' . $name . '_index_missing';\n\t\t\t\t} elseif ( $must_be_unique && ! $actual_indexes[ $name ] ) {\n\t\t\t\t\t$errors[] = $key . '_' . $name . '_unique_missing';\n\t\t\t\t}\n\t\t\t}\n""", """\t\t\t$actual_indexes = array();\n\t\t\tforeach ( $rows as $index ) {\n\t\t\t\t$name = (string) ( $index['Key_name'] ?? '' );\n\t\t\t\tif ( '' === $name ) { continue; }\n\t\t\t\tif ( ! isset( $actual_indexes[ $name ] ) ) { $actual_indexes[ $name ] = array( 'unique' => 0 === absint( $index['Non_unique'] ?? 1 ), 'columns' => array() ); }\n\t\t\t\t$seq = max( 1, absint( $index['Seq_in_index'] ?? 1 ) );\n\t\t\t\t$actual_indexes[ $name ]['columns'][ $seq ] = strtolower( (string) ( $index['Column_name'] ?? '' ) );\n\t\t\t}\n\t\t\tforeach ( $actual_indexes as &$index ) { ksort( $index['columns'], SORT_NUMERIC ); $index['columns'] = array_values( $index['columns'] ); } unset( $index );\n\t\t\tforeach ( $index_rules as $name => $rule ) {\n\t\t\t\t$must_be_unique = ! empty( $rule[0] ); $required_columns = array_map( 'strtolower', (array) ( $rule[1] ?? array() ) );\n\t\t\t\tif ( ! array_key_exists( $name, $actual_indexes ) ) { $errors[] = $key . '_' . $name . '_index_missing'; }\n\t\t\t\telseif ( $must_be_unique && empty( $actual_indexes[ $name ]['unique'] ) ) { $errors[] = $key . '_' . $name . '_unique_missing'; }\n\t\t\t\telseif ( $required_columns !== $actual_indexes[ $name ]['columns'] ) { $errors[] = $key . '_' . $name . '_columns_mismatch'; }\n\t\t\t}\n""")

# R17 — protected operators cannot mutate against a known unhealthy/mismatched File04 schema.
replace_once('includes/class-snfla-capabilities.php', """\t\tif ( ! self::file21_ready() ) {\n\t\t\treturn new WP_Error( 'snfla_file21_unavailable', 'Canonical File 21 is unavailable or incompatible.', array( 'status' => 503 ) );\n\t\t}\n\t\t$canonical_migration_authority""", """\t\tif ( ! self::file21_ready() ) {\n\t\t\treturn new WP_Error( 'snfla_file21_unavailable', 'Canonical File 21 is unavailable or incompatible.', array( 'status' => 503 ) );\n\t\t}\n\t\tif ( class_exists( 'SNFLA_Database' ) && ! SNFLA_Database::schema_healthy() ) {\n\t\t\treturn new WP_Error( 'snfla_schema_unhealthy', 'File 04 storage schema is not accepted for protected mutation.', array( 'status' => 503 ) );\n\t\t}\n\t\t$canonical_migration_authority""")

# R18/R19/R20 — exact opaque idempotency tokens and strictly positive unique object IDs at REST boundary.
replace_once('includes/class-snfla-rest.php', """\t\t$ids_arg = array( 'legacy_ids' => array( 'required' => true, 'type' => 'array', 'items' => array( 'type' => 'integer' ), 'validate_callback' => static function ( $value ) { return is_array( $value ) && count( $value ) >= 1 && count( $value ) <= SNFLA_Migration::MAX_BATCH; } ) );\n""", """\t\t$ids_arg = array( 'legacy_ids' => array( 'required' => true, 'type' => 'array', 'items' => array( 'type' => 'integer' ), 'validate_callback' => static function ( $value ) { if ( ! is_array( $value ) || count( $value ) < 1 || count( $value ) > SNFLA_Migration::MAX_BATCH ) return false; $ids = array(); foreach ( $value as $id ) { if ( ! is_int( $id ) && ! ( is_string( $id ) && preg_match( '/^[1-9][0-9]*$/D', $id ) ) ) return false; $id = (int) $id; if ( $id <= 0 || isset( $ids[ $id ] ) ) return false; $ids[ $id ] = true; } return true; } ) );\n""")
replace_once('includes/class-snfla-rest.php', """array( 'idempotency_key' => self::bounded_string_arg( false, 16, 190 ) )""", """array( 'idempotency_key' => self::opaque_idempotency_arg() )""")
replace_once('includes/class-snfla-rest.php', """array( 'idempotency_key' => self::bounded_string_arg( false, 16, 190 ), 'restore_handover'""", """array( 'idempotency_key' => self::opaque_idempotency_arg(), 'restore_handover'""")
replace_once('includes/class-snfla-rest.php', """\tprivate static function sha_arg() {\n""", """\tprivate static function opaque_idempotency_arg() {\n\t\treturn array( 'required' => false, 'type' => 'string', 'validate_callback' => static function ( $value ) { $value = (string) $value; $length = strlen( $value ); return 0 === $length || ( $length >= 16 && $length <= 190 && 1 === preg_match( '/^[!-~]+$/D', $value ) ); } );\n\t}\n\n\tprivate static function sha_arg() {\n""")
replace_once('includes/class-snfla-rest.php', """\t\t$header = trim( (string) $request->get_header( 'Idempotency-Key' ) );\n\t\t$body   = trim( (string) $request->get_param( 'idempotency_key' ) );\n""", """\t\t$header = (string) $request->get_header( 'Idempotency-Key' );\n\t\t$body   = (string) $request->get_param( 'idempotency_key' );\n""")

# R21/R22 — never surface timestamps/counts from unauthenticated (tampered) fallback/retirement evidence.
replace_once('includes/class-snfla-rest.php', """\t\t$window = get_option( SNFLA_Schema::FALLBACK_OPTION, array() );\n\t\treturn array( 'active' => SNFLA_Redirects::fallback_active(), 'opened_at_utc' => is_array( $window ) ? sanitize_text_field( (string) ( $window['opened_at_utc'] ?? '' ) ) : '', 'expires_at_utc' => is_array( $window ) ? sanitize_text_field( (string) ( $window['expires_at_utc'] ?? '' ) ) : '', 'read_only' => is_array( $window ) && ! empty( $window['read_only'] ) );\n""", """\t\t$window = get_option( SNFLA_Schema::FALLBACK_OPTION, array() );\n\t\t$trusted = SNFLA_Integrity::evidence_valid( $window );\n\t\treturn array( 'evidence_valid' => $trusted, 'active' => $trusted && SNFLA_Redirects::fallback_active(), 'opened_at_utc' => $trusted ? sanitize_text_field( (string) ( $window['opened_at_utc'] ?? '' ) ) : '', 'expires_at_utc' => $trusted ? sanitize_text_field( (string) ( $window['expires_at_utc'] ?? '' ) ) : '', 'read_only' => $trusted && ! empty( $window['read_only'] ) );\n""")
replace_once('includes/class-snfla-rest.php', """\t\t$evidence = get_option( SNFLA_Schema::RETIREMENT_OPTION, array() );\n\t\treturn array( 'recorded' => SNFLA_Integrity::evidence_valid( $evidence ), 'retired_at_utc' => is_array( $evidence ) ? sanitize_text_field( (string) ( $evidence['retired_at_utc'] ?? '' ) ) : '', 'source_retained' => is_array( $evidence ) && ! empty( $evidence['source_retained'] ), 'redirect_handoff_count' => is_array( $evidence ) ? absint( $evidence['redirect_handoff_count'] ?? 0 ) : 0 );\n""", """\t\t$evidence = get_option( SNFLA_Schema::RETIREMENT_OPTION, array() );\n\t\t$trusted = SNFLA_Integrity::evidence_valid( $evidence );\n\t\treturn array( 'recorded' => $trusted, 'retired_at_utc' => $trusted ? sanitize_text_field( (string) ( $evidence['retired_at_utc'] ?? '' ) ) : '', 'source_retained' => $trusted && ! empty( $evidence['source_retained'] ), 'redirect_handoff_count' => $trusted ? absint( $evidence['redirect_handoff_count'] ?? 0 ) : 0 );\n""")

# R23 — internal error metadata cannot create invalid HTTP status codes.
replace_once('includes/class-snfla-rest.php', """\t\t$status = is_array( $data ) && isset( $data['status'] ) ? absint( $data['status'] ) : 400;\n""", """\t\t$status = is_array( $data ) && isset( $data['status'] ) ? absint( $data['status'] ) : 400;\n\t\tif ( $status < 400 || $status > 599 ) { $status = 500; }\n""")

# R24/R25/R26 — mapping evidence encoding/decoding fails closed.
replace_once('includes/class-snfla-mapping.php', """\t\t$sql = $wpdb->prepare(\n\t\t\t\"INSERT INTO {$t['dry_run']} (run_uuid,source_signature,legacy_id,source_checksum,target_type,eligible,conflict_codes_json,created_at) VALUES (%s,%s,%d,%s,%s,%d,%s,%s) ON DUPLICATE KEY UPDATE source_signature=VALUES(source_signature),source_checksum=VALUES(source_checksum),target_type=VALUES(target_type),eligible=VALUES(eligible),conflict_codes_json=VALUES(conflict_codes_json),created_at=VALUES(created_at)\",\n""", """\t\t$conflicts_json = wp_json_encode( $conflicts, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES );\n\t\tif ( ! is_string( $conflicts_json ) ) { return false; }\n\t\t$sql = $wpdb->prepare(\n\t\t\t\"INSERT INTO {$t['dry_run']} (run_uuid,source_signature,legacy_id,source_checksum,target_type,eligible,conflict_codes_json,created_at) VALUES (%s,%s,%d,%s,%s,%d,%s,%s) ON DUPLICATE KEY UPDATE source_signature=VALUES(source_signature),source_checksum=VALUES(source_checksum),target_type=VALUES(target_type),eligible=VALUES(eligible),conflict_codes_json=VALUES(conflict_codes_json),created_at=VALUES(created_at)\",\n""")
replace_once('includes/class-snfla-mapping.php', """\t\t\twp_json_encode( $conflicts ),\n""", """\t\t\t$conflicts_json,\n""")
replace_once('includes/class-snfla-mapping.php', """\t\t$original = json_decode( (string) $row['original_json'], true );\n\t\t$original = is_array( $original ) ? $original : array();\n""", """\t\t$original = json_decode( (string) $row['original_json'], true );\n\t\tif ( ! is_array( $original ) || JSON_ERROR_NONE !== json_last_error() ) { return new WP_Error( 'snfla_interaction_original_corrupt' ); }\n""")
replace_once('includes/class-snfla-mapping.php', """\t\t$redacted = SNFLA_Audit::redact( $context );\n\t\t$fingerprint = SNFLA_Checksum::hash( array( $legacy_id, $code, $redacted ) );\n\t\t$sql = $wpdb->prepare(\n""", """\t\t$redacted = SNFLA_Audit::redact( $context );\n\t\t$redacted_json = wp_json_encode( $redacted, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES );\n\t\tif ( '' === $code || ! is_string( $redacted_json ) ) { return false; }\n\t\t$fingerprint = SNFLA_Checksum::hash( array( $legacy_id, $code, $redacted ) );\n\t\t$sql = $wpdb->prepare(\n""")
replace_once('includes/class-snfla-mapping.php', """\t\t\twp_json_encode( $redacted ),\n""", """\t\t\t$redacted_json,\n""")

# R27 — interaction cursor advances only after a source row was safely migrated/skipped.
replace_once('includes/class-snfla-interaction-provider.php', """\t\t\t\t\t$outcome = self::migrate_source_row( $kind, $legacy_id, $target_id, $source_row_id, $row, 'legacy_table' );\n\t\t\t\t\t$cursor = $source_row_id;\n\t\t\t\t\t$report['migrated'] += absint( $outcome['migrated'] ?? 0 );\n""", """\t\t\t\t\t$outcome = self::migrate_source_row( $kind, $legacy_id, $target_id, $source_row_id, $row, 'legacy_table' );\n\t\t\t\t\t$report['migrated'] += absint( $outcome['migrated'] ?? 0 );\n""")
replace_once('includes/class-snfla-interaction-provider.php', """\t\t\t\t\tif ( ! empty( $outcome['error'] ) ) {\n\t\t\t\t\t\t$report['errors'][] = sanitize_key( $outcome['error'] );\n\t\t\t\t\t\t$fatal = true;\n\t\t\t\t\t\tbreak;\n\t\t\t\t\t}\n""", """\t\t\t\t\tif ( ! empty( $outcome['error'] ) ) {\n\t\t\t\t\t\t$report['errors'][] = sanitize_key( $outcome['error'] );\n\t\t\t\t\t\t$fatal = true;\n\t\t\t\t\t\tbreak;\n\t\t\t\t\t}\n\t\t\t\t\t$cursor = $source_row_id;\n""")

# R28/R29 — core migrate/rollback functions preserve exact validated idempotency tokens.
replace_once('includes/class-snfla-migration.php', """\t\t$idempotency_key = trim( (string) $idempotency_key );\n\t\tif ( strlen( $idempotency_key ) < 16 || strlen( $idempotency_key ) > 190 ) { return new WP_Error( 'snfla_invalid_idempotency_key', 'A stable idempotency key of 16–190 characters is required.', array( 'status' => 400 ) ); }\n""", """\t\t$idempotency_key = (string) $idempotency_key;\n\t\tif ( strlen( $idempotency_key ) < 16 || strlen( $idempotency_key ) > 190 || 1 !== preg_match( '/^[!-~]+$/D', $idempotency_key ) ) { return new WP_Error( 'snfla_invalid_idempotency_key', 'A stable exact ASCII idempotency key of 16–190 non-space characters is required.', array( 'status' => 400 ) ); }\n""")
replace_once('includes/class-snfla-rollback.php', """\t\t$idempotency_key = trim( (string) $idempotency_key );\n\t\tif ( strlen( $idempotency_key ) < 16 || strlen( $idempotency_key ) > 190 ) { return new WP_Error( 'snfla_invalid_idempotency_key', 'A stable rollback idempotency key of 16–190 characters is required.', array( 'status' => 400 ) ); }\n""", """\t\t$idempotency_key = (string) $idempotency_key;\n\t\tif ( strlen( $idempotency_key ) < 16 || strlen( $idempotency_key ) > 190 || 1 !== preg_match( '/^[!-~]+$/D', $idempotency_key ) ) { return new WP_Error( 'snfla_invalid_idempotency_key', 'A stable exact ASCII rollback idempotency key of 16–190 non-space characters is required.', array( 'status' => 400 ) ); }\n""")

# R30 — restore table counts reject negative/non-integer/extra evidence instead of absint-normalizing it.
replace_once('includes/class-snfla-migration.php', """\t\t$restored_table_counts = isset( $evidence['restored_table_counts'] ) && is_array( $evidence['restored_table_counts'] ) ? array_map( 'absint', $evidence['restored_table_counts'] ) : array();\n\t\tforeach ( (array) ( $locked['table_counts'] ?? array() ) as $key => $count ) {\n""", """\t\t$restored_table_counts = isset( $evidence['restored_table_counts'] ) && is_array( $evidence['restored_table_counts'] ) ? $evidence['restored_table_counts'] : array();\n\t\t$expected_table_keys = array_keys( (array) ( $locked['table_counts'] ?? array() ) );\n\t\tif ( array_values( array_diff( array_keys( $restored_table_counts ), $expected_table_keys ) ) ) { return new WP_Error( 'snfla_restore_table_counts_invalid', 'Restore table-count evidence contains unexpected table keys.', array( 'status' => 400 ) ); }\n\t\tforeach ( $restored_table_counts as $key => $value ) { if ( false === filter_var( $value, FILTER_VALIDATE_INT, array( 'options' => array( 'min_range' => 0 ) ) ) ) return new WP_Error( 'snfla_restore_table_counts_invalid', 'Restore table counts must be non-negative integers.', array( 'status' => 400, 'table' => sanitize_key( $key ) ) ); $restored_table_counts[ $key ] = (int) $value; }\n\t\tforeach ( (array) ( $locked['table_counts'] ?? array() ) as $key => $count ) {\n""")

# R31 — inventory evidence rollback after failed lifecycle transition is verified, not assumed.
replace_once('includes/class-snfla-inventory.php', """\t\t\tif ( is_wp_error( $transition ) ) {\n\t\t\t\tupdate_option( SNFLA_Schema::INVENTORY_OPTION, $previous, false );\n\t\t\t\treturn $transition;\n\t\t\t}\n""", """\t\t\tif ( is_wp_error( $transition ) ) {\n\t\t\t\t$restored = update_option( SNFLA_Schema::INVENTORY_OPTION, $previous, false ) || get_option( SNFLA_Schema::INVENTORY_OPTION, array() ) === $previous;\n\t\t\t\treturn $restored ? $transition : new WP_Error( 'snfla_inventory_compensation_failed', 'Lifecycle transition failed and the previous inventory evidence could not be restored exactly.', array( 'status' => 500, 'cause' => $transition->get_error_code() ) );\n\t\t\t}\n""")

# R32 — backup proof compensation is verified.
replace_once('includes/class-snfla-migration.php', """\t\tif ( ! SNFLA_Audit::record( 'backup_restore_proof_recorded', $actor_id, array( 'backup_checksum' => $checksum, 'restore_checksum' => $restore_checksum, 'source_signature' => $source_signature, 'verifier_id' => $proof['verifier_id'], 'restored_at_utc' => $proof['restored_at_utc'] ), 'backup:' . $source_signature ) ) {\n\t\t\tupdate_option( SNFLA_Schema::BACKUP_PROOF_OPTION, $previous, false );\n\t\t\treturn new WP_Error( 'snfla_backup_proof_audit_failed', 'Backup/restore proof was reverted because its audit evidence could not be written.', array( 'status' => 500 ) );\n\t\t}\n""", """\t\tif ( ! SNFLA_Audit::record( 'backup_restore_proof_recorded', $actor_id, array( 'backup_checksum' => $checksum, 'restore_checksum' => $restore_checksum, 'source_signature' => $source_signature, 'verifier_id' => $proof['verifier_id'], 'restored_at_utc' => $proof['restored_at_utc'] ), 'backup:' . $source_signature ) ) {\n\t\t\t$restored_previous = update_option( SNFLA_Schema::BACKUP_PROOF_OPTION, $previous, false ) || get_option( SNFLA_Schema::BACKUP_PROOF_OPTION, array() ) === $previous;\n\t\t\treturn new WP_Error( $restored_previous ? 'snfla_backup_proof_audit_failed' : 'snfla_backup_proof_compensation_failed', $restored_previous ? 'Backup/restore proof was reverted because its audit evidence could not be written.' : 'Backup/restore audit failed and previous proof could not be restored exactly.', array( 'status' => 500, 'manual_recovery_required' => ! $restored_previous ) );\n\t\t}\n""")

# R33 — retirement evidence compensation is verified when final lifecycle transition fails.
replace_once('includes/class-snfla-retirement.php', """\t\t\tif ( is_wp_error( $transition ) ) { update_option( SNFLA_Schema::RETIREMENT_OPTION, $previous, false ); return $transition; }\n""", """\t\t\tif ( is_wp_error( $transition ) ) {\n\t\t\t\t$restored_previous = update_option( SNFLA_Schema::RETIREMENT_OPTION, $previous, false ) || get_option( SNFLA_Schema::RETIREMENT_OPTION, array() ) === $previous;\n\t\t\t\treturn $restored_previous ? $transition : new WP_Error( 'snfla_retirement_compensation_failed', 'Retirement transition failed and previous retirement evidence could not be restored exactly.', array( 'status' => 500, 'cause' => $transition->get_error_code(), 'manual_recovery_required' => true ) );\n\t\t\t}\n""")

# Release metadata to v2.0.4; no custom-table schema change.
replace_once('sabri-news-feed-legacy-adapter.php', 'three fresh ten-round hardening audits and safety controls.\n * Version: 2.0.3', 'three fresh ten-round hardening audits, an 80-round fresh hardening audit and safety controls.\n * Version: 2.0.4')
replace_once('sabri-news-feed-legacy-adapter.php', "define( 'SNFLA_VERSION', '2.0.3' );", "define( 'SNFLA_VERSION', '2.0.4' );")

print('Applied File 04 80-round corrective source patch through defect round 33.')
